### ISSUE TITLE
Framework for application development

### ISSUE THREAD

**Issue by Karlslopp** [gueleh/flowframework2#21]
Many enterprises today rely on the help of professionals in the framework for application development.  An important point for many of the companies that have contacted is an individual approach. An undoubted plus Scimus.com [https://thescimus.com/blog/how-to-choose-a-frontend-framework-for-web-development/](https://thescimus.com/blog/how-to-choose-a-frontend-framework-for-web-development/ ) the high quality of which is due to the specialized education of personnel and the use of the latest technologies when creating a product.

**Comment by gueleh** [comment]
How this does relate to this repository?
